module.exports = {
  arrowParens: 'avoid',
  bracketSameLine: true,
  bracketSpacing: true,
  singleQuote: true,
  trailingComma: 'es5',
  semi: true,
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrder: [
    '^react$',
    '^prop-types$',
    '^react-redux$',
    '^next/(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@components/(.*)$',
    '^@hooks/(.*)$',
    '^@utils/(.*)$',
    '^@constants/(.*)$',
    '^@styles/(.*)$',
    '^[./]',
  ],
};
