import Head from 'next/head';
import Header from '../components/common/Header';
import ProductList from '../components/ProductList';
import { gql } from '@apollo/client';
import client from '../apollo-client';
import ProductFilters from '../components/ProductFilters';

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="container mx-auto flex items-start flex-grow">
        <div className="w-64">
          <ProductFilters data={products} />
        </div>
        <div className="w-full pl-6">
          <ProductList data={products} />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { category } = ctx.query;
  const brands = ctx.query['brands[]'];

  console.log(brands);

  const { data } = await client.query({
    query: gql`
      query ($filter: ProductsFilter) {
        getProducts(filter: $filter) {
          category
          name
          image
          price
          sale_price
          subcategory
          brand
        }
      }
    `,
    variables: {
      filter: {
        ...(category ? { category } : null),
        ...(brands ? { brand: brands } : null),
      },
    },
  });

  return {
    props: {
      products: data.getProducts,
    },
  };
}
